services:
  app:
    container_name: rlabadie_jde-dev-terminal
    image: rlabadie_jde-dev:latest  # Build the image from your Dockerfile
    # user: app:rlabadie
    build:
      context: .  # Directory containing the Dockerfile
      dockerfile: Dockerfile  # Name of your Dockerfile
    environment:
      - BUFFER_SIZE=${BUFFER_SIZE}
    volumes:
      # - /mnt/nextcloud:/workspace/video_data
      - /home/rlabadie/jde:/workspace/code  # Mount the host folder to the container
      # - /home/rlabadie/anivision/routines:/workspace/code  # Mount the host folder to the container
    deploy: 
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["${GPUID}"] 
              capabilities: [gpu]
    # entrypoint: ["python3", "run.py"]  # Run the application
    cpuset: ${CPUSET}
    shm_size: '256gb'
    ports:
      - "0.0.0.0:10008:8000"  # Maps port 8000 in the container to 10008 on the host machine
    command: /bin/bash  # Default command when the container starts (interactive shell)
    stdin_open: true  # Keep STDIN open for interaction (for bash)
    tty: true  # Allocate a pseudo-TTY (for interactive shell)
    networks:
      - rlabadie_jde  # Connect to the custom network

networks:
  rlabadie_jde:
    name: rlabadie_jde  # You can set the custom network name here

    